application/controllers/Prueba.php, application/controllers/Remision.php, application/controllers/Venta.php, application/libraries/Pdfdos.php, application/libraries/fpdf/fpdf.php, application/models/Remision_producto_model.php, application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/remision/index.php, application/views/menu/venta/create.php
sactualizacion comprobantes Fixes #1
=> sactualizacion comprobantes Fixes #1

application/libraries/Pdfdos.php
=> subiendo cambios Fixes#5

application/libraries/Pdfdos.php
=> Carlosjunco#7

application/libraries/Pdfdos.php
=> subiendo cambios Fixes #9

application/libraries/Pdfdos.php
=> subiendo cambio Fixes #11

application/libraries/Pdfdos.php
=> subiendo cambios Fixes #13

application/libraries/Pdfdos.php
=> subiendo cambios Fixes #15

application/libraries/Pdfdos.php
=> subiendo cambios Fixes #17

application/libraries/Pdfdos.php
=> Correccion Fixes #19

application/libraries/Pdfdos.php
=> subiendo cambios Fixes #21

application/libraries/Pdfdos.php
=> subiendo cambios Fixes #23

application/controllers/Cpe.php, application/controllers/Prueba.php, application/controllers/Venta.php, application/libraries/Pdfdos.php, application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/venta/create_nota_credito.php, application/views/menu/venta/index.php, application/views/menu/venta/nota_credito.php
Subiendo cambios Fixes #25
SQL
=====================================================================
ALTER TABLE `factura_nota_credito` ADD `numero_nota` INT(6) NOT NULL AFTER `descripcion_nota`;
ALTER TABLE `factura_nota_credito` ADD `external_id_modificado` VARCHAR(500) NULL AFTER `numero_nota`;
ALTER TABLE ``factura_nota_credito`` DROP INDEX ``serie``;
=> Subiendo cambios Fixes #25

application/views/menu/venta/create_nota_credito.php
=> subiendo cambio Fixes #27

application/models/Venta_model.php, application/views/menu/venta/nota_credito.php
=> subiendo cambios Fixes #29

application/libraries/Pdfdos.php
=> subiendo cambios FIxes #31

application/libraries/Pdfdos.php, application/views/menu/venta/nota_credito.php
=> Cambios Fixes #33

application/libraries/Pdfdos.php
=> subiendo cambio Fixes #35

application/libraries/Pdfdos.php, application/libraries/fpdf/fpdf.php
=> subiendo cambios Fixes #37

application/libraries/Pdfdos.php
=> subiendo cambios Fixes #39

application/libraries/Pdfdos.php
=> cambios Fixes #41

application/controllers/Cpe.php, application/controllers/Venta.php, application/models/Venta_model.php
=> sbuendo cambios Fixes #43

application/controllers/Cpe.php, application/views/menu/venta/nota_credito.php
=> subiendo cambios Fixes #45

application/views/menu/venta/nota_credito.php
=> subiendo cambio Fixes #47

application/controllers/Cpe.php, application/views/menu/venta/nota_credito.php
=> subiendo cambio Fixes #49

application/controllers/Cpe.php, application/views/layout/bottom.php
=> subiendo camibos Fixes #51

application/controllers/Cpe.php, application/libraries/Pdfdos.php, application/views/layout/bottom.php
=> cambios comprobante Fixes #53

application/controllers/Venta.php, application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/venta/anulaciones.php, application/views/menu/venta/index.php
=> subiendo cambios Fixes #55

application/controllers/Venta.php, application/libraries/Pdfdos.php, application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/venta/anulaciones.php, application/views/menu/venta/index.php
=> Cambios Fixes #57

application/controllers/Prueba.php, application/controllers/Venta.php, application/libraries/Pdfdos.php, application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/venta/index.php, application/views/menu/venta/nota_credito.php
=> subiendo cambio Fixes #59

application/libraries/Pdfdos.php, application/models/Venta_model.php, application/views/menu/venta/index.php, application/views/menu/venta/nota_credito.php
=> Cambios Fixes #62

application/libraries/Pdfdos.php
=> cambio subido Fixes #64

application/controllers/Cpe.php, application/controllers/Venta.php, application/models/Venta_model.php, application/views/menu/venta/create.php
=> subiendo cambios Fixes #66

application/views/layout/bottom.php
=> subiendo cambios Fixes #68

application/libraries/Pdfdos.php
=> subiendo cambio Fixes #70

application/controllers/Cpe.php, application/controllers/Gestion.php, application/controllers/Venta.php, application/libraries/Pdfdos.php, application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/venta/create.php, application/views/menu/venta/index.php
subiendo cambios Fixes #72
SQL
===============================================================================
ALTER TABLE venta ADD guia_remision_ids VARCHAR(500) NULL AFTER observacion, ADD guia_remision_numeros VARCHAR(500) NULL AFTER guia_remision_ids;
update venta set guia_remision_ids=remision_id, guia_remision_numeros=guia_remision
==================================================================
=> subiendo cambios Fixes #72

application/views/menu/remision/index.php
=> subiendo cambios Fixes #74

application/libraries/Pdfdos.php, application/views/layout/bottom.php
=> subiendo cambios Fixes #76

application/views/layout/bottom.php
=> subiendo cambios Fixes #78

application/controllers/Cpe.php, application/libraries/fpdf/fpdf.php
=> subiendo cambio Fixes #80

application/controllers/Cpe.php, application/controllers/Venta.php, application/models/Guia_model.php, application/models/Venta_model.php
cambio liberacion guia de remision al anular o nota de credito Fixes #82
=> cambio liberacion guia de remision al anular o nota de credito Fixes #82

application/controllers/Cpe.php, application/controllers/Venta.php
=> subiendo cambios Fixes #84

application/controllers/Cpe.php, application/controllers/Venta.php, application/libraries/Pdfdos.php, application/models/Venta_model.php, application/views/menu/venta/create.php
=> subiendo cambios FIxes #86

application/controllers/Cliente.php, application/views/menu/cliente/detalles.php, application/views/menu/cliente/index.php, application/views/menu/venta/create.php
=> Tipo de direccion Fixes #88

application/controllers/Cliente.php, application/models/Cliente_direccion_model.php, application/views/layout/bottom.php, application/views/menu/cliente/index.php
modal direcciones Fixes #90
ALTER TABLE `cliente_direccion` CHANGE `ubigeo` `ubigeo` VARCHAR(10) NULL DEFAULT NULL;
=> modal direcciones Fixes #90

application/controllers/Venta.php, application/libraries/Pdfdos.php, application/models/Venta_model.php
=> subiendo cambios Fixes #92

application/controllers/Cpe.php, application/controllers/Venta.php, application/models/Venta_model.php, application/views/menu/venta/create.php
=> subiendo cambio Fixes #94

application/views/layout/bottom.php, application/views/menu/remision/create.php
Analisis + solucion producto editado edicion Fixes #96
=> Analisis + solucion producto editado edicion Fixes #96

application/libraries/Pdfdos.php
=> tamaño observacoin Fixes #100

application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/remision/index.php
=> Orden remision Fixes #102

application/controllers/Cpe.php, application/models/Guia_model.php, application/models/Venta_model.php, application/views/layout/bottom.php, application/views/menu/remision/index.php, application/views/menu/venta/index.php
=>  consulta sunat Fixes #104

application/controllers/Prueba.php, application/libraries/Pdfdos.php, application/libraries/fpdf/fpdf.php
=> QR CAMBIO FIxes #107

application/controllers/Venta.php, application/libraries/Pdfdos.php, application/models/Venta_model.php, application/views/menu/venta/create.php, css/viatmc/viatmc.css, db_viatmc_estable.sql
implementacion de credito, credito con cuotas en venta/create, registro de informacion extra y envio a API de tipo de condicion de pago y cuotas si corresponde.
adicion de CONDICION DE PAGO en el reporte de Factura A4
para la Base de Datos
```
-- ejecutar 30-10-2021
ALTER TABLE venta ADD COLUMN condicion_pago VARCHAR(50);
ALTER TABLE venta ADD COLUMN credito_con_cuotas TEXT(0);
ALTER TABLE venta ADD COLUMN credito_metodo_pago VARCHAR(50);
ALTER TABLE venta ADD COLUMN credito_fecha DATE;
ALTER TABLE venta ADD COLUMN credito_monto DOUBLE(11, 2);
```
=> implementacion credito - condicion de pago - reporte
